### PR TITLE
Rebuilt as dotnet core project

### PR DESCRIPTION
**Pull request by apawsey**
Removed string intern, and serialization
Rebuilt test project against xunit
Compatibility for net 2+ and net standard 1+

Please give some feedback on whether this will happen?  If not we must publish as a new nuget package!

### CODE REVIEW

**Comment by niemyjski** [comment]
@apawsey this will happen. I'm going to create a new branch called `feature/dotnet` and will start working on this. Would you mind doing a pr for just the test changes and we'll work on this together incrementally against latest tooling. I see some changes in here that should be behind a compiler directive and is supported in .net core rtm.

**Comment by niemyjski** [comment]
I'm going to close this as it would be more work to accept this and upgrade to latest tooling than to just do the conversion against latest .net core rtm.

**Comment by apawsey** [comment]
@niemyjski What changes do you think should be behind a compiler directive?  As far as I know, nothing would needs to change for rtm.

**Comment by niemyjski** [comment]
Please take a look at the new pr. I put all serialization behind the compiler directive.

Get Outlook for iOS




On Wed, Jul 20, 2016 at 6:48 AM -0500, "Adam" <notifications@github.com> wrote:












@niemyjski What changes do you think should be behind a compiler directive?  As far as I know, nothing would needs to change for rtm.

**Pull request closed without merging**
